name: Deploy Streamlit Dashboard

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533267120119:role/OIDC-ROLE
          aws-region: us-east-1

      - name: Deploy to EC2 using SSM
        shell: bash
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-004e985e0bab8c1bf" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "set -e",

              "sudo dnf install -y git python3 python3-pip python3.11",

              "mkdir -p /home/ec2-user",

              "if [ ! -d /home/ec2-user/dashboard/.git ]; then git clone https://github.com/kashifsayyad09/pipeline-dashboard.git /home/ec2-user/dashboard; fi",

              "cd /home/ec2-user/dashboard",

              "git fetch origin",
              "git reset --hard origin/main",

              "rm -f .env",

              "echo GITHUB_TOKEN=${{ secrets.TOKEN_APP }} > .env",
              "echo GITHUB_API_URL=${{ secrets.API_URL }} >> .env",

              "echo ==== ENV FILE ====",
              "cat .env",

              "rm -rf venv",

              "python3.11 -m venv venv",

              "venv/bin/python --version",

              "venv/bin/python -m pip install --upgrade pip setuptools wheel",

              "venv/bin/python -m pip install --no-cache-dir -r requirements.txt",

              "pkill -f streamlit || true",

              "nohup venv/bin/streamlit run app.py --server.address=0.0.0.0 --server.port=8501 > streamlit.log 2>&1 &",

              "sleep 15",

              "echo ==== STREAMLIT LOG ====",
              "cat streamlit.log || true",

              "echo ==== PROCESS ====",
              "pgrep -af streamlit || true"
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"

          set +e

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "i-004e985e0bab8c1bf"

          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "i-004e985e0bab8c1bf" \
            --output json

          STATUS=$(aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "i-004e985e0bab8c1bf" \
            --query "Status" \
            --output text)

          echo "Deployment Status: $STATUS"

          if [ "$STATUS" != "Success" ]; then
            exit 1
          fi

      - name: Deployment Complete
        run: echo "✅ Deployment Successful"
