name: Deploy Streamlit Dashboard

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533267120119:role/OIDC-ROLE
          aws-region: us-east-1

      - name: Deploy using SSM
        shell: bash
        run: |

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids i-004e985e0bab8c1bf \
            --document-name AWS-RunShellScript \
            --parameters 'commands=[
              "set -e",

              "sudo dnf install -y git python3 python3-pip",

              "mkdir -p /home/ec2-user",

              "if [ ! -d /home/ec2-user/dashboard ]; then git clone https://github.com/kashifsayyad09/pipeline-dashboard.git /home/ec2-user/dashboard; fi",

              "cd /home/ec2-user/dashboard",

              "git reset --hard",

              "git clean -fd",

              "git pull origin main",

              "cp -f .env.example .env",

              "echo GITHUB_TOKEN=${{ secrets.TOKEN_APP }} >> .env",

              "echo GITHUB_API_URL=${{ secrets.API_URL }} >> .env",

              "python3 -m pip install -r requirements.txt",

              "pkill -f streamlit || true",

              "nohup streamlit run app.py --server.address=0.0.0.0 --server.port=8501 > streamlit.log 2>&1 &",

              "sleep 15",

              "cat streamlit.log || true",

              "pgrep -af streamlit || true"
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id i-004e985e0bab8c1bf || true

          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id i-004e985e0bab8c1bf \
            --output json

          STATUS=$(aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id i-004e985e0bab8c1bf \
            --query Status \
            --output text)

          echo "Deployment Status: $STATUS"

          if [ "$STATUS" != "Success" ]; then
            exit 1
          fi
